class WorldSpawn:
    def __init__(self):...
    def newWorld(self):
        pass
    def generalUpdate(self):...
    def clientUpdate(self):...
    def serverUpdate(self):...

def getObject():
    return WorldSpawn